@baseUrl = http://localhost:3000

# RECADOS
### RecadosControllerFindAll
# @name RecadosControllerFindAll
GET {{baseUrl}}/recados/
# ?limit=10
# &offset=10

### RecadosControllerFindOne
# @name RecadosControllerFindOne
GET {{baseUrl}}/recados/7

### RecadosControllerCreate
# @name RecadosControllerCreate
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Prova de Programação Básica",
    "deId": 6,
    "paraId": 2
}

### RecadosControllerUpdate
# @name RecadosControllerUpdate
PATCH  {{baseUrl}}/recados/2
Content-Type: application/json

{
    "para": "TESTE"
}

### RecadosControllerRemove
# @name RecadosControllerRemove
DELETE {{baseUrl}}/recados/3

# PESSOAS
@rota_pessoa = pessoas
### PessoasControllerFindAll
# @name PessoasControllerFindAll
GET {{baseUrl}}/{{rota_pessoa}}/
# ?limit=10
# &offset=10

### PessoasControllerFindOne
# @name PessoasControllerFindOne
GET {{baseUrl}}/{{rota_pessoa}}/2

### PessoasControllerCreate
# @name PessoasControllerCreate
POST {{baseUrl}}/{{rota_pessoa}}/
Content-Type: application/json

{
    "nome": "Rodrigo Gomide",
    "email": "rodrigo.gomide@ifgoiano.edu.br",
    "password": "123456"
}

### PessoasControllerUpdate
# @name PessoasControllerUpdate
PATCH  {{baseUrl}}/{{rota_pessoa}}/2
Content-Type: application/json

{
    "nome": "TESTE",
    "password": "TESTE"
}

### PessoasControllerRemove
# @name PessoasControllerRemove
DELETE {{baseUrl}}/{{rota_pessoa}}/2