@baseUrl = http://localhost:3000

### RecadosControllerFindAll
# @name RecadosControllerFindAll
GET {{baseUrl}}/recados/
# ?limit=10
# &offset=10

### RecadosControllerFindOne
# @name RecadosControllerFindOne
GET {{baseUrl}}/recados/2

### RecadosControllerCreate
# @name RecadosControllerCreate
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Novo Recado",
    "de": "Denecley Alvim",
    "para": "Nanaxara",
    "lido": false,
    "data": "2024-11-03T16:22:40.421Z"
}

### RecadosControllerUpdate
# @name RecadosControllerUpdate
PATCH  {{baseUrl}}/recados/2
Content-Type: application/json

{
    "texto": "Novo Recado",
    "de": "Denecley Alvim",
    "para": "Nanaxara",
    "lido": true,
    "data": "2024-11-03T16:22:40.421Z"
}

### RecadosControllerRemove
# @name RecadosControllerRemove
DELETE {{baseUrl}}/recados/2